### PR TITLE
test(AnyToAny): extract base tests for anytoany

### PR DESCRIPTION
**Pull request by 0xruhum**
- removed the univ3 oracle stuff
- removed the base implementation from `BaseStrategy._totalAssets()` so that any contract inheriting the contract has to override it
- extracted the base AnyToAny tests into their own file
- added the boilerplate setup for AnyCompounderNaive

### CODE REVIEW

**Comment by RedVeil** [comment]
@0xruhum There are still 2 TODOs left in the AnyConverter which both look reasonable

**Comment by RedVeil** [comment]
@0xruhum In `_claimReserved` it seems unlikely that we have two claims for asset and yieldAsset. Since if both is required you'd just adjust the amount in `pull` / `push`. If i want to push 100 assets and pull 50 assets id essentialy just push 50 assets.

**Comment by RedVeil** [comment]
@0xruhum I like the favorable rate logic but couldnt we run into an issue in which we didnt reserve enough tokens since the rates changed?

**Comment by 0xruhum** [comment]
1. Ah yes got to address those
2. True we could just force the user to parse the asset that they want to claim or a bool (isYield)
3. No i don't think so. We only ever reserve more than necessary

**Pull request merged**
